title: Zekai Wu's Homepage
page-top-title: Zekai Wu
top-section-bg-text: Be what you wanna be
home-subtitle: 吴泽凯 | Zekai Wu | 博士在读 | 东华大学
copyright-text: '&copy; Zekai Wu 2023-2025. All Rights Reserved.'
