title: Zekai Wu's Homepage
page-top-title: Zekai Wu's Homepage
top-section-bg-text: Materials design is a subtle balance between simplicity and complexity
home-subtitle: 吴泽凯 | Zekai Wu | 2026博士毕业 | 东华大学
copyright-text: '&copy; Zekai Wu 2023-2025. All Rights Reserved.'
